image: ruby:2.7

pages:
  stage: deploy
  script:
  - mkdir public
  - echo "Installing Java..."
  - apt-get update
  - apt-get -y install default-jdk

  - echo "Creating documentation..."
  - mkdir doc
  - wget https://github.com/dgarijo/Widoco/releases/download/v1.4.15/widoco-1.4.15-jar-with-dependencies.jar -O widoco.jar
  - java -jar widoco.jar -ontFile ifcrml.rdf -outFolder doc -webVowl -uniteSections -rewriteAll -oops
  - mv doc/doc/index-en.html doc/doc/index.html
  # Fix broken OOPS link
  - sed -i 's/<!-- <dt>Evaluation/<dt>Evaluation/g' doc/doc/index.html
  - sed -i 's/OOPS!" \/><\/a><\/dd> -->/OOPS!" \/><\/a><\/dd> /g' doc/doc/index.html
  - sed -i 's/OOPSEvaluation\/oopsEval.html/OOPSevaluation\/oopsEval.html/g' doc/doc/index.html
 
  - echo "Copying results to /public for publishing..."
  - cp -r doc/doc/* public
  artifacts:
    paths:
    - public
  only:
  - master
